/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export type Time = bigint;
export interface DigitalResource {
    id: string;
    url: string;
    title: string;
    description: string;
    addedAt: Time;
    category: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Reservation {
    id: string;
    status: ReservationStatus;
    userId: Principal;
    createdAt: Time;
    dueDate?: Time;
    bookId: string;
    updatedAt: Time;
}
export interface Book {
    id: string;
    title: string;
    availableCopies: bigint;
    file?: ExternalBlob;
    isbn: string;
    description: string;
    author: string;
    totalCopies: bigint;
    addedAt: Time;
    category: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface BookCreateData {
    title: string;
    file?: ExternalBlob;
    isbn: string;
    description: string;
    author: string;
    totalCopies: bigint;
    category: string;
}
export interface BorrowRecord {
    id: string;
    borrowedAt: Time;
    dueDate: Time;
    bookId: string;
    returnedAt?: Time;
}
export interface Announcement {
    id: string;
    title: string;
    publishDate: Time;
    body: string;
    createdAt: Time;
    updatedAt: Time;
    priority: AnnouncementPriority;
}
export interface AnnouncementCreateData {
    title: string;
    publishDate: Time;
    body: string;
    priority: AnnouncementPriority;
}
export interface UserProfile {
    name: string;
    joinedAt: Time;
    role: string;
    email: string;
}
export interface DigitalResourceCreateData {
    url: string;
    title: string;
    description: string;
    category: string;
}
export enum AnnouncementPriority {
    normal = "normal",
    urgent = "urgent"
}
export enum ReservationStatus {
    cancelled = "cancelled",
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addAnnouncement(data: AnnouncementCreateData): Promise<string>;
    addBook(bookCreateData: BookCreateData): Promise<void>;
    addDigitalResource(data: DigitalResourceCreateData): Promise<string>;
    approveReservation(reservationId: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    borrowBook(bookId: string): Promise<void>;
    cancelReservation(reservationId: string): Promise<void>;
    createReservation(bookId: string): Promise<string>;
    decrementActiveUsers(): Promise<void>;
    deleteAnnouncement(announcementId: string): Promise<void>;
    deleteBook(bookId: string): Promise<void>;
    deleteDigitalResource(resourceId: string): Promise<void>;
    editAnnouncement(announcementId: string, data: AnnouncementCreateData): Promise<void>;
    editBook(bookId: string, bookCreateData: BookCreateData): Promise<void>;
    editDigitalResource(resourceId: string, data: DigitalResourceCreateData): Promise<void>;
    getActiveUserCount(): Promise<bigint>;
    getAllAnnouncements(): Promise<Array<Announcement>>;
    getAllBooksSortedByTitle(): Promise<Array<Book>>;
    getAllBorrowRecords(): Promise<Array<[Principal, Array<BorrowRecord>]>>;
    getAllDigitalResources(): Promise<Array<DigitalResource>>;
    getAllReservations(): Promise<Array<Reservation>>;
    getAllUsers(): Promise<Array<[Principal, UserProfile]>>;
    getBookById(id: string): Promise<Book>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDashboardStats(): Promise<{
        overdueCount: bigint;
        booksBorrowed: bigint;
        totalUsers: bigint;
        totalBooks: bigint;
    }>;
    getMyBorrowHistory(): Promise<Array<BorrowRecord>>;
    getMyReservations(): Promise<Array<Reservation>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUserRole(): Promise<UserRole>;
    incrementActiveUsers(): Promise<void>;
    initialize(adminToken: string, userProvidedToken: string): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    rejectReservation(reservationId: string): Promise<void>;
    returnBook(bookId: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
}
import type { Announcement as _Announcement, AnnouncementCreateData as _AnnouncementCreateData, AnnouncementPriority as _AnnouncementPriority, Book as _Book, BookCreateData as _BookCreateData, BorrowRecord as _BorrowRecord, ExternalBlob as _ExternalBlob, Reservation as _Reservation, ReservationStatus as _ReservationStatus, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addAnnouncement(arg0: AnnouncementCreateData): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addAnnouncement(to_candid_AnnouncementCreateData_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAnnouncement(to_candid_AnnouncementCreateData_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addBook(arg0: BookCreateData): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addBook(await to_candid_BookCreateData_n12(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBook(await to_candid_BookCreateData_n12(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addDigitalResource(arg0: DigitalResourceCreateData): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addDigitalResource(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDigitalResource(arg0);
            return result;
        }
    }
    async approveReservation(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveReservation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveReservation(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n15(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n15(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async borrowBook(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.borrowBook(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.borrowBook(arg0);
            return result;
        }
    }
    async cancelReservation(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelReservation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelReservation(arg0);
            return result;
        }
    }
    async createReservation(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createReservation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createReservation(arg0);
            return result;
        }
    }
    async decrementActiveUsers(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.decrementActiveUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.decrementActiveUsers();
            return result;
        }
    }
    async deleteAnnouncement(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAnnouncement(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAnnouncement(arg0);
            return result;
        }
    }
    async deleteBook(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBook(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBook(arg0);
            return result;
        }
    }
    async deleteDigitalResource(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDigitalResource(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDigitalResource(arg0);
            return result;
        }
    }
    async editAnnouncement(arg0: string, arg1: AnnouncementCreateData): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editAnnouncement(arg0, to_candid_AnnouncementCreateData_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editAnnouncement(arg0, to_candid_AnnouncementCreateData_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async editBook(arg0: string, arg1: BookCreateData): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editBook(arg0, await to_candid_BookCreateData_n12(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editBook(arg0, await to_candid_BookCreateData_n12(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async editDigitalResource(arg0: string, arg1: DigitalResourceCreateData): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editDigitalResource(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editDigitalResource(arg0, arg1);
            return result;
        }
    }
    async getActiveUserCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveUserCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveUserCount();
            return result;
        }
    }
    async getAllAnnouncements(): Promise<Array<Announcement>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAnnouncements();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAnnouncements();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllBooksSortedByTitle(): Promise<Array<Book>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBooksSortedByTitle();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBooksSortedByTitle();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllBorrowRecords(): Promise<Array<[Principal, Array<BorrowRecord>]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBorrowRecords();
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBorrowRecords();
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllDigitalResources(): Promise<Array<DigitalResource>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDigitalResources();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDigitalResources();
            return result;
        }
    }
    async getAllReservations(): Promise<Array<Reservation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllReservations();
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllReservations();
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUsers(): Promise<Array<[Principal, UserProfile]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return result;
        }
    }
    async getBookById(arg0: string): Promise<Book> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookById(arg0);
                return from_candid_Book_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookById(arg0);
            return from_candid_Book_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardStats(): Promise<{
        overdueCount: bigint;
        booksBorrowed: bigint;
        totalUsers: bigint;
        totalBooks: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return result;
        }
    }
    async getMyBorrowHistory(): Promise<Array<BorrowRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyBorrowHistory();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyBorrowHistory();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyReservations(): Promise<Array<Reservation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyReservations();
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyReservations();
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserRole();
                return from_candid_UserRole_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserRole();
            return from_candid_UserRole_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async incrementActiveUsers(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.incrementActiveUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.incrementActiveUsers();
            return result;
        }
    }
    async initialize(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initialize(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initialize(arg0, arg1);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async rejectReservation(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectReservation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectReservation(arg0);
            return result;
        }
    }
    async returnBook(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.returnBook(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.returnBook(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
}
function from_candid_AnnouncementPriority_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AnnouncementPriority): AnnouncementPriority {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_Announcement_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Announcement): Announcement {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
async function from_candid_Book_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Book): Promise<Book> {
    return await from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_BorrowRecord_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BorrowRecord): BorrowRecord {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_ReservationStatus_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReservationStatus): ReservationStatus {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function from_candid_Reservation_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Reservation): Reservation {
    return from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n26(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    publishDate: _Time;
    body: string;
    createdAt: _Time;
    updatedAt: _Time;
    priority: _AnnouncementPriority;
}): {
    id: string;
    title: string;
    publishDate: Time;
    body: string;
    createdAt: Time;
    updatedAt: Time;
    priority: AnnouncementPriority;
} {
    return {
        id: value.id,
        title: value.title,
        publishDate: value.publishDate,
        body: value.body,
        createdAt: value.createdAt,
        updatedAt: value.updatedAt,
        priority: from_candid_AnnouncementPriority_n20(_uploadFile, _downloadFile, value.priority)
    };
}
async function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    availableCopies: bigint;
    file: [] | [_ExternalBlob];
    isbn: string;
    description: string;
    author: string;
    totalCopies: bigint;
    addedAt: _Time;
    category: string;
}): Promise<{
    id: string;
    title: string;
    availableCopies: bigint;
    file?: ExternalBlob;
    isbn: string;
    description: string;
    author: string;
    totalCopies: bigint;
    addedAt: Time;
    category: string;
}> {
    return {
        id: value.id,
        title: value.title,
        availableCopies: value.availableCopies,
        file: record_opt_to_undefined(await from_candid_opt_n25(_uploadFile, _downloadFile, value.file)),
        isbn: value.isbn,
        description: value.description,
        author: value.author,
        totalCopies: value.totalCopies,
        addedAt: value.addedAt,
        category: value.category
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    borrowedAt: _Time;
    dueDate: _Time;
    bookId: string;
    returnedAt: [] | [_Time];
}): {
    id: string;
    borrowedAt: Time;
    dueDate: Time;
    bookId: string;
    returnedAt?: Time;
} {
    return {
        id: value.id,
        borrowedAt: value.borrowedAt,
        dueDate: value.dueDate,
        bookId: value.bookId,
        returnedAt: record_opt_to_undefined(from_candid_opt_n32(_uploadFile, _downloadFile, value.returnedAt))
    };
}
function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _ReservationStatus;
    userId: Principal;
    createdAt: _Time;
    dueDate: [] | [_Time];
    bookId: string;
    updatedAt: _Time;
}): {
    id: string;
    status: ReservationStatus;
    userId: Principal;
    createdAt: Time;
    dueDate?: Time;
    bookId: string;
    updatedAt: Time;
} {
    return {
        id: value.id,
        status: from_candid_ReservationStatus_n36(_uploadFile, _downloadFile, value.status),
        userId: value.userId,
        createdAt: value.createdAt,
        dueDate: record_opt_to_undefined(from_candid_opt_n32(_uploadFile, _downloadFile, value.dueDate)),
        bookId: value.bookId,
        updatedAt: value.updatedAt
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_tuple_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, Array<_BorrowRecord>]): [Principal, Array<BorrowRecord>] {
    return [
        value[0],
        from_candid_vec_n29(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    normal: null;
} | {
    urgent: null;
}): AnnouncementPriority {
    return "normal" in value ? AnnouncementPriority.normal : "urgent" in value ? AnnouncementPriority.urgent : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): ReservationStatus {
    return "cancelled" in value ? ReservationStatus.cancelled : "pending" in value ? ReservationStatus.pending : "approved" in value ? ReservationStatus.approved : "rejected" in value ? ReservationStatus.rejected : value;
}
function from_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Announcement>): Array<Announcement> {
    return value.map((x)=>from_candid_Announcement_n18(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Book>): Promise<Array<Book>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Book_n23(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, Array<_BorrowRecord>]>): Array<[Principal, Array<BorrowRecord>]> {
    return value.map((x)=>from_candid_tuple_n28(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BorrowRecord>): Array<BorrowRecord> {
    return value.map((x)=>from_candid_BorrowRecord_n30(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Reservation>): Array<Reservation> {
    return value.map((x)=>from_candid_Reservation_n34(_uploadFile, _downloadFile, x));
}
function to_candid_AnnouncementCreateData_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AnnouncementCreateData): _AnnouncementCreateData {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_AnnouncementPriority_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AnnouncementPriority): _AnnouncementPriority {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
async function to_candid_BookCreateData_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookCreateData): Promise<_BookCreateData> {
    return await to_candid_record_n13(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_UserRole_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    file?: ExternalBlob;
    isbn: string;
    description: string;
    author: string;
    totalCopies: bigint;
    category: string;
}): Promise<{
    title: string;
    file: [] | [_ExternalBlob];
    isbn: string;
    description: string;
    author: string;
    totalCopies: bigint;
    category: string;
}> {
    return {
        title: value.title,
        file: value.file ? candid_some(await to_candid_ExternalBlob_n14(_uploadFile, _downloadFile, value.file)) : candid_none(),
        isbn: value.isbn,
        description: value.description,
        author: value.author,
        totalCopies: value.totalCopies,
        category: value.category
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    publishDate: Time;
    body: string;
    priority: AnnouncementPriority;
}): {
    title: string;
    publishDate: _Time;
    body: string;
    priority: _AnnouncementPriority;
} {
    return {
        title: value.title,
        publishDate: value.publishDate,
        body: value.body,
        priority: to_candid_AnnouncementPriority_n10(_uploadFile, _downloadFile, value.priority)
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AnnouncementPriority): {
    normal: null;
} | {
    urgent: null;
} {
    return value == AnnouncementPriority.normal ? {
        normal: null
    } : value == AnnouncementPriority.urgent ? {
        urgent: null
    } : value;
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
