/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const BookCreateData = IDL.Record({
  'title' : IDL.Text,
  'isbn' : IDL.Text,
  'description' : IDL.Text,
  'author' : IDL.Text,
  'totalCopies' : IDL.Nat,
  'category' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Book = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'availableCopies' : IDL.Nat,
  'isbn' : IDL.Text,
  'description' : IDL.Text,
  'author' : IDL.Text,
  'totalCopies' : IDL.Nat,
  'addedAt' : Time,
  'category' : IDL.Text,
});
export const BorrowRecord = IDL.Record({
  'id' : IDL.Text,
  'borrowedAt' : Time,
  'dueDate' : Time,
  'bookId' : IDL.Text,
  'returnedAt' : IDL.Opt(Time),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'joinedAt' : Time,
  'role' : IDL.Text,
  'email' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBook' : IDL.Func([BookCreateData], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'borrowBook' : IDL.Func([IDL.Text], [], []),
  'getAllBooksSortedByTitle' : IDL.Func([], [IDL.Vec(Book)], ['query']),
  'getAllBorrowRecords' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(BorrowRecord)))],
      ['query'],
    ),
  'getAllUsers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  'getBookById' : IDL.Func([IDL.Text], [Book], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'overdueCount' : IDL.Nat,
          'booksBorrowed' : IDL.Nat,
          'totalUsers' : IDL.Nat,
          'totalBooks' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getMyBorrowHistory' : IDL.Func([], [IDL.Vec(BorrowRecord)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'returnBook' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const BookCreateData = IDL.Record({
    'title' : IDL.Text,
    'isbn' : IDL.Text,
    'description' : IDL.Text,
    'author' : IDL.Text,
    'totalCopies' : IDL.Nat,
    'category' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Book = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'availableCopies' : IDL.Nat,
    'isbn' : IDL.Text,
    'description' : IDL.Text,
    'author' : IDL.Text,
    'totalCopies' : IDL.Nat,
    'addedAt' : Time,
    'category' : IDL.Text,
  });
  const BorrowRecord = IDL.Record({
    'id' : IDL.Text,
    'borrowedAt' : Time,
    'dueDate' : Time,
    'bookId' : IDL.Text,
    'returnedAt' : IDL.Opt(Time),
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'joinedAt' : Time,
    'role' : IDL.Text,
    'email' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBook' : IDL.Func([BookCreateData], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'borrowBook' : IDL.Func([IDL.Text], [], []),
    'getAllBooksSortedByTitle' : IDL.Func([], [IDL.Vec(Book)], ['query']),
    'getAllBorrowRecords' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(BorrowRecord)))],
        ['query'],
      ),
    'getAllUsers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    'getBookById' : IDL.Func([IDL.Text], [Book], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'overdueCount' : IDL.Nat,
            'booksBorrowed' : IDL.Nat,
            'totalUsers' : IDL.Nat,
            'totalBooks' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getMyBorrowHistory' : IDL.Func([], [IDL.Vec(BorrowRecord)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'returnBook' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };