/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Announcement {
  'id' : string,
  'title' : string,
  'publishDate' : Time,
  'body' : string,
  'createdAt' : Time,
  'updatedAt' : Time,
  'priority' : AnnouncementPriority,
}
export interface AnnouncementCreateData {
  'title' : string,
  'publishDate' : Time,
  'body' : string,
  'priority' : AnnouncementPriority,
}
export type AnnouncementPriority = { 'normal' : null } |
  { 'urgent' : null };
export interface Book {
  'id' : string,
  'title' : string,
  'availableCopies' : bigint,
  'isbn' : string,
  'description' : string,
  'author' : string,
  'totalCopies' : bigint,
  'addedAt' : Time,
  'category' : string,
}
export interface BookCreateData {
  'title' : string,
  'isbn' : string,
  'description' : string,
  'author' : string,
  'totalCopies' : bigint,
  'category' : string,
}
export interface BorrowRecord {
  'id' : string,
  'borrowedAt' : Time,
  'dueDate' : Time,
  'bookId' : string,
  'returnedAt' : [] | [Time],
}
export interface DigitalResource {
  'id' : string,
  'url' : string,
  'title' : string,
  'description' : string,
  'addedAt' : Time,
  'category' : string,
}
export interface DigitalResourceCreateData {
  'url' : string,
  'title' : string,
  'description' : string,
  'category' : string,
}
export interface Reservation {
  'id' : string,
  'status' : ReservationStatus,
  'userId' : Principal,
  'createdAt' : Time,
  'dueDate' : [] | [Time],
  'bookId' : string,
  'updatedAt' : Time,
}
export type ReservationStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'joinedAt' : Time,
  'role' : string,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAnnouncement' : ActorMethod<[AnnouncementCreateData], string>,
  'addBook' : ActorMethod<[BookCreateData], undefined>,
  'addDigitalResource' : ActorMethod<[DigitalResourceCreateData], string>,
  'approveReservation' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'borrowBook' : ActorMethod<[string], undefined>,
  'cancelReservation' : ActorMethod<[string], undefined>,
  'createReservation' : ActorMethod<[string], string>,
  'decrementActiveUsers' : ActorMethod<[], undefined>,
  'deleteAnnouncement' : ActorMethod<[string], undefined>,
  'deleteBook' : ActorMethod<[string], undefined>,
  'deleteDigitalResource' : ActorMethod<[string], undefined>,
  'editAnnouncement' : ActorMethod<[string, AnnouncementCreateData], undefined>,
  'editBook' : ActorMethod<[string, BookCreateData], undefined>,
  'editDigitalResource' : ActorMethod<
    [string, DigitalResourceCreateData],
    undefined
  >,
  'getActiveUserCount' : ActorMethod<[], bigint>,
  'getAllAnnouncements' : ActorMethod<[], Array<Announcement>>,
  'getAllBooksSortedByTitle' : ActorMethod<[], Array<Book>>,
  'getAllBorrowRecords' : ActorMethod<
    [],
    Array<[Principal, Array<BorrowRecord>]>
  >,
  'getAllDigitalResources' : ActorMethod<[], Array<DigitalResource>>,
  'getAllReservations' : ActorMethod<[], Array<Reservation>>,
  'getAllUsers' : ActorMethod<[], Array<[Principal, UserProfile]>>,
  'getBookById' : ActorMethod<[string], Book>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardStats' : ActorMethod<
    [],
    {
      'overdueCount' : bigint,
      'booksBorrowed' : bigint,
      'totalUsers' : bigint,
      'totalBooks' : bigint,
    }
  >,
  'getMyBorrowHistory' : ActorMethod<[], Array<BorrowRecord>>,
  'getMyReservations' : ActorMethod<[], Array<Reservation>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserRole' : ActorMethod<[], UserRole>,
  'incrementActiveUsers' : ActorMethod<[], undefined>,
  'initialize' : ActorMethod<[string, string], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'rejectReservation' : ActorMethod<[string], undefined>,
  'returnBook' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];