/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Book {
  'id' : string,
  'title' : string,
  'availableCopies' : bigint,
  'isbn' : string,
  'description' : string,
  'author' : string,
  'totalCopies' : bigint,
  'addedAt' : Time,
  'category' : string,
}
export interface BookCreateData {
  'title' : string,
  'isbn' : string,
  'description' : string,
  'author' : string,
  'totalCopies' : bigint,
  'category' : string,
}
export interface BorrowRecord {
  'id' : string,
  'borrowedAt' : Time,
  'dueDate' : Time,
  'bookId' : string,
  'returnedAt' : [] | [Time],
}
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'joinedAt' : Time,
  'role' : string,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBook' : ActorMethod<[BookCreateData], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'borrowBook' : ActorMethod<[string], undefined>,
  'getAllBooksSortedByTitle' : ActorMethod<[], Array<Book>>,
  'getAllBorrowRecords' : ActorMethod<
    [],
    Array<[Principal, Array<BorrowRecord>]>
  >,
  'getAllUsers' : ActorMethod<[], Array<[Principal, UserProfile]>>,
  'getBookById' : ActorMethod<[string], Book>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardStats' : ActorMethod<
    [],
    {
      'overdueCount' : bigint,
      'booksBorrowed' : bigint,
      'totalUsers' : bigint,
      'totalBooks' : bigint,
    }
  >,
  'getMyBorrowHistory' : ActorMethod<[], Array<BorrowRecord>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'returnBook' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];